{% set name = "langgraph" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdb824bf29e98c3bda73f06eda8f44d10fe766a977f252c92e58ee1a0a83973d
  patches:
    # E   ModuleNotFoundError: No module named 'psycopg-pool'
    # E   ModuleNotFoundError: No module named 'langgraph-checkpoint-postgres'
    # E   ModuleNotFoundError: No module named 'langgraph-checkpoint-sqlite'
    # E   ModuleNotFoundError: No module named 'langgraph.cache.redis'
    - patches/0001-removed-pool-and-unavailable-checkpointers.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - langchain-core >=0.1
    - langgraph-checkpoint >=2.1.0,<3.0.0
    - langgraph-sdk >=0.2.2,<0.3.0
    - langgraph-prebuilt >=0.6.0,<0.7.0
    - python-xxhash >=3.5.0
    - pydantic >=2.7.4

# E   ModuleNotFoundError: No module named 'syrupy'
{% set ignore_tests = " --ignore=tests/test_large_cases.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_large_cases_async.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_pregel.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_pregel_async.py" %}
# E   NotImplementedError: Unknown checkpointer: postgres_aio_pool -> No module named 'psycopg-pool'
{% set tests_to_skip = "test_interruption_without_state_updates_async" %}
# E   httpcore.ConnectError: All connection attempts failed
{% set tests_to_skip = tests_to_skip + " or test_remote_graph_basic_invoke" %}
{% set tests_to_skip = tests_to_skip + " or test_remote_graph_stream_messages_tuple" %}
# E           NameError: name '_checkpointer_postgres_pool' is not defined
# E           NameError: name '_checkpointer_postgres_aio_pool' is not defined
# E           NameError: name '_checkpointer_sqlite_aes' is not defined
# E           NameError: name '_checkpointer_sqlite' is not defined
{% set tests_to_skip = tests_to_skip + " or test_interruption_without_state_updates" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_checkpoint_migration.py" %}

test:
  source_files:
    - tests
  imports:
    - langgraph
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    - psycopg
    - redis

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Building stateful, multi-actor applications with LLMs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Trusted by companies shaping the future of agents - including Klarna, Replit, Elastic, and more - LangGraph
    is a low-level orchestration framework for building, managing, and deploying long-running, stateful agents.
  doc_url: https://langchain-ai.github.io/langgraph
  dev_url: https://www.github.com/langchain-ai/langgraph

extra:
  recipe-maintainers:
    - jan-janssen
