{% set name = "langgraph" %}
{% set version = "0.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langgraph-{{ version }}.tar.gz
  sha256: 435e2bff165d526236294eac03b5e848653ed4d9ba2373e36432e3ca3e952ebe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - langgraph-checkpoint >=1.0.2,<2.0.0
    - python >=3.9.0,<4.0
    - langchain-core >=0.2.27,<0.3

test:
  imports:
    - langgraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: langgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
