{% set name = "langgraph" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph-{{ version }}.tar.gz
  sha256: 8948a35f6f85805c8ac36e94d5492c86a34c39dcf6f405b0f84491bc444e3479

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - pydantic >=2.7.4
    - python-xxhash >=3.5.0
    - langgraph-prebuilt >=0.2.0
    - langgraph-sdk >=0.1.42
    - langgraph-checkpoint >=2.0.26
    - langchain-core >=0.1

test:
  imports:
    - langgraph
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Building stateful, multi-actor applications with LLMs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Trusted by companies shaping the future of agents - including Klarna, Replit, Elastic, and more - LangGraph
    is a low-level orchestration framework for building, managing, and deploying long-running, stateful agents.
  doc_url: https://langchain-ai.github.io/langgraph
  dev_url: https://www.github.com/langchain-ai/langgraph

extra:
  recipe-maintainers:
    - jan-janssen
