{% set python_min = "3.9.0" %}
{% set name = "langgraph" %}
{% set version = "0.3.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph-{{ version }}.tar.gz
  sha256: c76bbc8f26604929d6c2520d937b5602d5bb1dde2c0580398d015f7f6841f14c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python-xxhash >=3.5.0,<4.0.0
    - langgraph-prebuilt >=0.1.8,<0.2
    - langgraph-sdk >=0.1.42,<0.2.0
    - langgraph-checkpoint >=2.0.10,<3.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=0.1,<0.4

test:
  imports:
    - langgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: langgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
